### PR TITLE
chore(api): Change `controllers` array to `roster_members` in division roster api

### LINKED ISSUE #877: VATEUD API Changes
These are the changes in VATEUD API that we should also comply with. Until then backwards combability is available.

- [ ] GET Roster endpoint `/api/facility/roster` has a new return `roster_members` with user_cid and permitted_upto (rating). This will replace the `controllers` array which only contained id's earlier https://discord.com/channels/380821811006406667/1176178753597087834/1219946147729117204

### PR DESCRIPTION
**Pull request by mufassilyasir**
I may have not ran the command locally, so please do @blt950 😅 

This closes #877

### CODE REVIEW

**Comment by blt950** [comment]
I tried to run it locally @mufassilyasir but I get some server errors.
```root@4a401d4218aa:/app# php artisan sync:roster
Syncing roster with Division API...
Adding new members to roster...
Failed to add member 10000004 to roster: Server Error
Failed to add member 10000051 to roster: No query results for model [App\Models\User] 10000051
Failed to add member 10000096 to roster: No query results for model [App\Models\User] 10000096
Failed to add member 10000201 to roster: No query results for model [App\Models\User] 10000201
Failed to add member 10000022 to roster: No query results for model [App\Models\User] 10000022
Failed to add member 10000003 to roster: Server Error
Failed to add member 10000002 to roster: Server Error
Failed to add member 10000077 to roster: No query results for model [App\Models\User] 10000077
Failed to add member 10000008 to roster: No query results for model [App\Models\User] 10000008
Removing members from roster...
Syncing roster with Division API completed.```

Those query model errors are fine, as they're just user who doesn't exist in your test env.

**Comment by mufassilyasir** [comment]
@blt950 Did you run the test with core-dev or core (prod)?

**Comment by blt950** [comment]
@mufassilyasir 
It's in the test env, so I run it for core-dev indeed. You want me to test dev users (1000001-10) on the prod env instead? I don't really want to make an release just to test this on prod-data, to find out something fails 😅

**Comment by mufassilyasir** [comment]
I'll get back to you when I can regarding testing in the dev env. 

I don't know why I am not getting notifications on this PR...

**Comment by blt950** [comment]
> I'll get back to you when I can regarding testing in the dev env.
> 
> I don't know why I am not getting notifications on this PR...

Any update on this one?

**Comment by blt950** [comment]
Thanks to the dev test I found one error that I tweaked so the script behaved the same as always.

**Pull request merged**
