### PR TITLE
misc: add another docker-compose file with database & Redis

### PR DESCRIPTION
**Pull request by thor**
Add a `docker-compose.full.yml` which includes both a MariaDB database and a Redis instance.

### CODE REVIEW

**Comment by thor** [comment]
It's a straightforward fix, but chucking you in as a reviewer @blt950 as I'd prefer to not revert it at a later point. ;)

**Comment by blt950** [comment]
I disagree with this addition, the production environment docs says to get your own DB, and I think this should be reflected in the development composer as well. BYOD (Bring your own database)

**Comment by thor** [comment]
> I disagree with this addition; the production environment docs says to get your own DB, and I think this should be reflected in the development composer as well. BYOD (Bring your own database)

Then we'll have to agree to disagree. 

To make it easier to get set up with a _development_  (not production) instance, reducing as many barriers as possible is not uncommon by providing an example setup with all the components. That reduces the effort to get started while providing a common baseline for testing other components such as database, caching (Redis), etc.

Let me know how you'd like to proceed.

**Comment by thor** [comment]
@blt950 updated as a new file. 👀

**Comment by blt950** [comment]
> @blt950 updated as a new file. 👀

docker-compose.full.yaml is for production or development? Thought I perhaps misunderstood that you wanted a dev compose with database, not prod?

**Comment by thor** [comment]
> > @blt950 updated as a new file. 👀
> 
> docker-compose.full.yaml is for production or development? Thought I perhaps misunderstood that you wanted a dev compose with database, not prod?

Yup, it is a compose file for development. We could rename it to `dev.full` if you'd like.

**Comment by blt950** [comment]
> > > @blt950 updated as a new file. 👀
> > 
> > 
> > docker-compose.full.yaml is for production or development? Thought I perhaps misunderstood that you wanted a dev compose with database, not prod?
> 
> Yup, it is a compose file for development. We could rename it to `dev.full` if you'd like.

That'd make more sense as I thought this was suddenly for production use :D Once that's done I'm happy and you can merge

**Comment by thor** [comment]
Done-done.

**Review by blt950 — APPROVED** [review]
I approve this message, merge when you want

**Pull request merged**
